import { useState } from 'react';
import { Settings as SettingsIcon, Bell, Database, Shield, Save } from 'lucide-react';
export default function SettingsPage() {
  const [activeTab, setActiveTab] = useState('general');
  const [saved, setSaved] = useState(false);
  const [settings, setSettings] = useState({ companyName: 'Donnet SA', adminEmail: 'soporte@donnet.com.ar', lowStockThreshold: 3, maintenanceIntervalDays: 90, enableEmailAlerts: true, enableDesktopNotifications: true, meshUrl: 'mesh.donnet.com.ar', workHoursStart: '08:00', workHoursEnd: '18:00' });
  function handleSave() { setSaved(true); setTimeout(function() { setSaved(false); }, 3000); }
  var tabs = [{ id: 'general', label: 'General', icon: SettingsIcon }, { id: 'notifications', label: 'Notificaciones', icon: Bell }, { id: 'monitoring', label: 'Monitoreo', icon: Database }, { id: 'security', label: 'Seguridad', icon: Shield }];
  var inputCls = "w-full px-4 py-2.5 bg-white/5 border border-white/10 rounded-xl text-sm text-white focus:outline-none focus:ring-2 focus:ring-blue-500/50";
  return (<div className="space-y-6">
    <div><h1 className="text-2xl lg:text-3xl font-bold text-white">Configuracion</h1><p className="text-slate-400 text-sm mt-1">Ajustes del sistema</p></div>
    <div className="flex gap-2 flex-wrap">{tabs.map(function(tab) { var Icon = tab.icon; return (<button key={tab.id} onClick={function() { setActiveTab(tab.id); }} className={"flex items-center gap-2 px-4 py-2.5 rounded-xl text-sm font-medium transition-all " + (activeTab === tab.id ? 'bg-blue-500/20 text-blue-400 border border-blue-500/30' : 'bg-white/5 text-slate-400 border border-white/10 hover:bg-white/10')}><Icon className="w-4 h-4" />{tab.label}</button>); })}</div>
    <div className="glass-card p-6">
      {activeTab === 'general' && <div className="space-y-6"><div className="flex items-center gap-3 mb-6"><div className="w-10 h-10 rounded-xl bg-blue-500/20 flex items-center justify-center"><SettingsIcon className="w-5 h-5 text-blue-400" /></div><div><h2 className="text-lg font-semibold text-white">Configuracion General</h2></div></div>
        <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
          <div><label className="block text-sm font-medium text-slate-300 mb-2">Empresa</label><input type="text" value={settings.companyName} onChange={function(e) { setSettings(Object.assign({}, settings, { companyName: e.target.value })); }} className={inputCls} /></div>
          <div><label className="block text-sm font-medium text-slate-300 mb-2">Email Admin</label><input type="email" value={settings.adminEmail} onChange={function(e) { setSettings(Object.assign({}, settings, { adminEmail: e.target.value })); }} className={inputCls} /></div>
          <div><label className="block text-sm font-medium text-slate-300 mb-2">Umbral Stock Bajo</label><input type="number" value={settings.lowStockThreshold} onChange={function(e) { setSettings(Object.assign({}, settings, { lowStockThreshold: parseInt(e.target.value) || 0 })); }} className={inputCls} /></div>
          <div><label className="block text-sm font-medium text-slate-300 mb-2">Intervalo Mant. (dias)</label><input type="number" value={settings.maintenanceIntervalDays} onChange={function(e) { setSettings(Object.assign({}, settings, { maintenanceIntervalDays: parseInt(e.target.value) || 0 })); }} className={inputCls} /></div></div></div>}
      {activeTab === 'notifications' && <div className="space-y-4"><div className="flex items-center gap-3 mb-6"><div className="w-10 h-10 rounded-xl bg-purple-500/20 flex items-center justify-center"><Bell className="w-5 h-5 text-purple-400" /></div><div><h2 className="text-lg font-semibold text-white">Notificaciones</h2></div></div>
        <div className="flex items-center justify-between p-4 rounded-xl bg-white/5 border border-white/10"><div><p className="text-sm font-medium text-white">Alertas por Email</p><p className="text-xs text-slate-400">Stock bajo y mantenimiento</p></div>
          <button onClick={function() { setSettings(Object.assign({}, settings, { enableEmailAlerts: !settings.enableEmailAlerts })); }} className={"w-12 h-6 rounded-full transition-all " + (settings.enableEmailAlerts ? 'bg-blue-500' : 'bg-white/20')}><div className={"w-5 h-5 rounded-full bg-white shadow-sm transition-transform " + (settings.enableEmailAlerts ? 'translate-x-6' : 'translate-x-0.5')} /></button></div>
        <div className="flex items-center justify-between p-4 rounded-xl bg-white/5 border border-white/10"><div><p className="text-sm font-medium text-white">Notificaciones Desktop</p><p className="text-xs text-slate-400">Push en el navegador</p></div>
          <button onClick={function() { setSettings(Object.assign({}, settings, { enableDesktopNotifications: !settings.enableDesktopNotifications })); }} className={"w-12 h-6 rounded-full transition-all " + (settings.enableDesktopNotifications ? 'bg-blue-500' : 'bg-white/20')}><div className={"w-5 h-5 rounded-full bg-white shadow-sm transition-transform " + (settings.enableDesktopNotifications ? 'translate-x-6' : 'translate-x-0.5')} /></button></div></div>}
      {activeTab === 'monitoring' && <div className="space-y-6"><div className="flex items-center gap-3 mb-6"><div className="w-10 h-10 rounded-xl bg-emerald-500/20 flex items-center justify-center"><Database className="w-5 h-5 text-emerald-400" /></div><div><h2 className="text-lg font-semibold text-white">Monitoreo Mesh</h2><p className="text-xs text-slate-400">Configuracion de mesh.donnet.com.ar</p></div></div>
        <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
          <div><label className="block text-sm font-medium text-slate-300 mb-2">URL Mesh</label><input type="text" value={settings.meshUrl} onChange={function(e) { setSettings(Object.assign({}, settings, { meshUrl: e.target.value })); }} className={inputCls} /></div>
          <div><label className="block text-sm font-medium text-slate-300 mb-2">Horario Inicio</label><input type="time" value={settings.workHoursStart} onChange={function(e) { setSettings(Object.assign({}, settings, { workHoursStart: e.target.value })); }} className={inputCls} /></div>
          <div><label className="block text-sm font-medium text-slate-300 mb-2">Horario Fin</label><input type="time" value={settings.workHoursEnd} onChange={function(e) { setSettings(Object.assign({}, settings, { workHoursEnd: e.target.value })); }} className={inputCls} /></div></div>
        <div className="p-4 rounded-xl bg-blue-500/10 border border-blue-500/20"><p className="text-sm text-blue-400">Las PCs que esten encendidas fuera del horario {settings.workHoursStart} - {settings.workHoursEnd} generaran alertas automaticas.</p></div></div>}
      {activeTab === 'security' && <div className="space-y-4"><div className="flex items-center gap-3 mb-6"><div className="w-10 h-10 rounded-xl bg-red-500/20 flex items-center justify-center"><Shield className="w-5 h-5 text-red-400" /></div><div><h2 className="text-lg font-semibold text-white">Seguridad</h2></div></div>
        <div className="p-4 rounded-xl bg-white/5 border border-white/10"><p className="text-sm text-white font-medium">Autenticacion activa</p><p className="text-xs text-slate-400 mt-1">Sistema protegido con credenciales de administrador</p></div>
        <div className="p-4 rounded-xl bg-white/5 border border-white/10"><p className="text-sm text-white font-medium">Permisos por rol</p><p className="text-xs text-slate-400 mt-1">Admin, Operador y Visualizador con permisos diferenciados</p></div></div>}
      <div className="mt-8 pt-6 border-t border-white/10 flex items-center justify-between">
        <p className="text-xs text-slate-500">{saved ? '✅ Cambios guardados' : 'Los cambios se aplicaran al guardar'}</p>
        <button onClick={handleSave} className={"flex items-center gap-2 px-6 py-2.5 rounded-xl text-sm font-medium " + (saved ? 'bg-emerald-500/20 text-emerald-400 border border-emerald-500/30' : 'bg-blue-500 text-white hover:bg-blue-600')}><Save className="w-4 h-4" />{saved ? 'Guardado' : 'Guardar Cambios'}</button></div></div></div>);
}